#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall `sdl-config --cflags`
RESINC = 
LIBDIR = 
LIB = -lSDL_image
LDFLAGS = `sdl-config --libs`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/GameSDL

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/GameSDL

OBJ_DEBUG = $(OBJDIR_DEBUG)/CApp_putGem.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/CSurface.o $(OBJDIR_DEBUG)/CGem.o $(OBJDIR_DEBUG)/CEvent.o $(OBJDIR_DEBUG)/CApp_verifyAllMatrix.o $(OBJDIR_DEBUG)/CApp_onRender.o $(OBJDIR_DEBUG)/CApp_onLoop.o $(OBJDIR_DEBUG)/CApp_onInit.o $(OBJDIR_DEBUG)/CApp_onEvent.o $(OBJDIR_DEBUG)/CApp_onCleanup.o $(OBJDIR_DEBUG)/CApp_neighbours.o $(OBJDIR_DEBUG)/CApp_makeSwitchGems.o $(OBJDIR_DEBUG)/CApp_collapseGems.o $(OBJDIR_DEBUG)/CApp_collapseCase.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/CApp_putGem.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/CSurface.o $(OBJDIR_RELEASE)/CGem.o $(OBJDIR_RELEASE)/CEvent.o $(OBJDIR_RELEASE)/CApp_verifyAllMatrix.o $(OBJDIR_RELEASE)/CApp_onRender.o $(OBJDIR_RELEASE)/CApp_onLoop.o $(OBJDIR_RELEASE)/CApp_onInit.o $(OBJDIR_RELEASE)/CApp_onEvent.o $(OBJDIR_RELEASE)/CApp_onCleanup.o $(OBJDIR_RELEASE)/CApp_neighbours.o $(OBJDIR_RELEASE)/CApp_makeSwitchGems.o $(OBJDIR_RELEASE)/CApp_collapseGems.o $(OBJDIR_RELEASE)/CApp_collapseCase.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/CApp_putGem.o: CApp_putGem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_putGem.cpp -o $(OBJDIR_DEBUG)/CApp_putGem.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/CSurface.o: CSurface.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CSurface.cpp -o $(OBJDIR_DEBUG)/CSurface.o

$(OBJDIR_DEBUG)/CGem.o: CGem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CGem.cpp -o $(OBJDIR_DEBUG)/CGem.o

$(OBJDIR_DEBUG)/CEvent.o: CEvent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CEvent.cpp -o $(OBJDIR_DEBUG)/CEvent.o

$(OBJDIR_DEBUG)/CApp_verifyAllMatrix.o: CApp_verifyAllMatrix.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_verifyAllMatrix.cpp -o $(OBJDIR_DEBUG)/CApp_verifyAllMatrix.o

$(OBJDIR_DEBUG)/CApp_onRender.o: CApp_onRender.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_onRender.cpp -o $(OBJDIR_DEBUG)/CApp_onRender.o

$(OBJDIR_DEBUG)/CApp_onLoop.o: CApp_onLoop.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_onLoop.cpp -o $(OBJDIR_DEBUG)/CApp_onLoop.o

$(OBJDIR_DEBUG)/CApp_onInit.o: CApp_onInit.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_onInit.cpp -o $(OBJDIR_DEBUG)/CApp_onInit.o

$(OBJDIR_DEBUG)/CApp_onEvent.o: CApp_onEvent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_onEvent.cpp -o $(OBJDIR_DEBUG)/CApp_onEvent.o

$(OBJDIR_DEBUG)/CApp_onCleanup.o: CApp_onCleanup.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_onCleanup.cpp -o $(OBJDIR_DEBUG)/CApp_onCleanup.o

$(OBJDIR_DEBUG)/CApp_neighbours.o: CApp_neighbours.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_neighbours.cpp -o $(OBJDIR_DEBUG)/CApp_neighbours.o

$(OBJDIR_DEBUG)/CApp_makeSwitchGems.o: CApp_makeSwitchGems.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_makeSwitchGems.cpp -o $(OBJDIR_DEBUG)/CApp_makeSwitchGems.o

$(OBJDIR_DEBUG)/CApp_collapseGems.o: CApp_collapseGems.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_collapseGems.cpp -o $(OBJDIR_DEBUG)/CApp_collapseGems.o

$(OBJDIR_DEBUG)/CApp_collapseCase.o: CApp_collapseCase.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CApp_collapseCase.cpp -o $(OBJDIR_DEBUG)/CApp_collapseCase.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/CApp_putGem.o: CApp_putGem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_putGem.cpp -o $(OBJDIR_RELEASE)/CApp_putGem.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/CSurface.o: CSurface.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CSurface.cpp -o $(OBJDIR_RELEASE)/CSurface.o

$(OBJDIR_RELEASE)/CGem.o: CGem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CGem.cpp -o $(OBJDIR_RELEASE)/CGem.o

$(OBJDIR_RELEASE)/CEvent.o: CEvent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CEvent.cpp -o $(OBJDIR_RELEASE)/CEvent.o

$(OBJDIR_RELEASE)/CApp_verifyAllMatrix.o: CApp_verifyAllMatrix.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_verifyAllMatrix.cpp -o $(OBJDIR_RELEASE)/CApp_verifyAllMatrix.o

$(OBJDIR_RELEASE)/CApp_onRender.o: CApp_onRender.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_onRender.cpp -o $(OBJDIR_RELEASE)/CApp_onRender.o

$(OBJDIR_RELEASE)/CApp_onLoop.o: CApp_onLoop.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_onLoop.cpp -o $(OBJDIR_RELEASE)/CApp_onLoop.o

$(OBJDIR_RELEASE)/CApp_onInit.o: CApp_onInit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_onInit.cpp -o $(OBJDIR_RELEASE)/CApp_onInit.o

$(OBJDIR_RELEASE)/CApp_onEvent.o: CApp_onEvent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_onEvent.cpp -o $(OBJDIR_RELEASE)/CApp_onEvent.o

$(OBJDIR_RELEASE)/CApp_onCleanup.o: CApp_onCleanup.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_onCleanup.cpp -o $(OBJDIR_RELEASE)/CApp_onCleanup.o

$(OBJDIR_RELEASE)/CApp_neighbours.o: CApp_neighbours.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_neighbours.cpp -o $(OBJDIR_RELEASE)/CApp_neighbours.o

$(OBJDIR_RELEASE)/CApp_makeSwitchGems.o: CApp_makeSwitchGems.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_makeSwitchGems.cpp -o $(OBJDIR_RELEASE)/CApp_makeSwitchGems.o

$(OBJDIR_RELEASE)/CApp_collapseGems.o: CApp_collapseGems.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_collapseGems.cpp -o $(OBJDIR_RELEASE)/CApp_collapseGems.o

$(OBJDIR_RELEASE)/CApp_collapseCase.o: CApp_collapseCase.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CApp_collapseCase.cpp -o $(OBJDIR_RELEASE)/CApp_collapseCase.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

